// Generates src/openapi.d.ts from the FastAPI app (ADR-003).
// Usage: `pnpm --filter @atu/types gen`  |  `--check` fails if the committed file is stale.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const apiDir = resolve(here, "../../../services/api");
const outFile = resolve(here, "../src/openapi.d.ts");
const check = process.argv.includes("--check");

const schemaJson = execFileSync("uv", ["run", "--quiet", "python", "-m", "scripts.export_openapi"], {
  cwd: apiDir,
  encoding: "utf8",
});

const ast = await openapiTS(JSON.parse(schemaJson));
const header = "// Generated by packages/types/scripts/generate.mjs from the FastAPI OpenAPI schema. Do not edit.\n\n";
const output = header + astToString(ast);

if (check) {
  let current = "";
  try {
    current = readFileSync(outFile, "utf8");
  } catch {
    // missing file counts as stale
  }
  if (current !== output) {
    console.error("packages/types is out of date. Run `pnpm --filter @atu/types gen` and commit.");
    process.exit(1);
  }
  console.log("packages/types is up to date.");
} else {
  writeFileSync(outFile, output);
  console.log(`Wrote ${outFile}`);
}
